services:
  apidrf:
    build: ./
    volumes:
      - ./:/home/appuser
    ports:
      - 8000:8000
    restart: always
    env_file:
      .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
