services:
  apidrf:
    build: ./
    volumes:
      - ./:/home/appuser
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=drf_dev

volumes:
  postgres_data:
