name: tests

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branchs:
#       - 'feature/**'
#       - 'fix/**'
#       - 'refactor/**'


jobs:
  test:
    runs-on: ubuntu-22.04
    name: Tests
    steps:
      - name: checkout PR merge commit
        uses: actions/checkout@v4

      - name: Test docker
        run: |
          docker --version
          docker images
          ls -alh
