name: tests

# on: workflow_dispatch
on:
   push:
     branches:
       - main
   pull_request:
     branchs:
       - 'feature/**'
       - 'fix/**'
       - 'adjusts/**'


jobs:
  test:
    runs-on: ubuntu-22.04
    name: Tests
    steps:
      - name: checkout PR merge commit
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          curl -L \
          "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose \
          && sudo chmod +x /usr/local/bin/docker-compose \
          && docker-compose --version

      - name: Test docker
        run: |
          docker --version
          docker images
          cp -v .env.example .env
          docker-compose down --volumes \
          && docker-compose up --detach --build \
          && docker-compose exec apidrf python manage.py test
          docker images
